### ISSUE TITLE
How does one "give" a repo to haskell?

### ISSUE THREAD

**Issue by TomMD** [haskell/meta#3]
I am tired of being sole maintainer and think the community needs more maintainer groups. How could I give my repos to the haskell group?

**Comment by Bodigrim** [comment]
I'm not sure I see a relationship: in general moving a repo under github.com/haskell umbrella does not come with free maintainers available.

Some packages can be donated to CLC, which will be responsible to find new maintainers. See https://github.com/haskell/core-libraries-committee#core-libraries.

**Comment by TomMD** [comment]
>  does not come with free maintainers available.

**Comment by TomMD** [comment]
>  does not come with free maintainers available.

Yep. I would expect to join the group at the same time. This is intended as a more general question than my specific case. The `haskell` group has nothing in the way of normal operations. How packages or maintainers join and depart is a bit opaque. What is its affiliation. What, if anything, are the promises or reasonable expectations. It seems like we have an opportunity to spell things out a bit even if things aren't a good fit for my specific packages.

**Comment by TomMD** [comment]
@Bodigrim Is there more to "I'm not sure I see a relationship" beyond a distaste for people expecting free maintenance? As stated, I'm happy to be a maintainer and just think packages should have many. It would also be enlightening to learn if there is a particular charter for github.com/haskell that spells out the types of packages which excludes this one in particular.

**Comment by Bodigrim** [comment]
Oh, I'm sorry if my remark sounded unnecessary harsh. But I'm genuinely confused about the relationship. I mean, you can add as many maintainers as you like to a repo under your personal namespace, right? You don't have to transfer it to another organisation just for the sake of this.

> which excludes this one in particular.

Which one?

**Comment by TomMD** [comment]
> Which one?

The repository of immediate interest to me is `entropy`. It deserves a better home.

> you can add as many maintainers as you like to a repo under your personal namespace, right?

Yes, absolutely right. However, there's value in a more known, accessible, central group of maintainers which isn't solved by me seeking out and adding some to my particular repository. From what I'm hearing on discourse and twitter this has already been thought of under the name "haskell-party", but there isn't any progress. This idea is what I thought the github.com/haskell group was aimed at solving, but I don't understand it's charter at all (clearly).

At this point the discussion is evolving into more of a community talk on how we might organize a group of maintainers of not-quite core libraries. Perfect for discourse but sub-optimal for github issues so I'll close the ticket.

**Comment by Bodigrim** [comment]
Given that `entropy` is a dependency of `lsp` (via `uuid`) and crucial for many parts of ecosystem, I'd support its adoption by CLC, if you wish to pursue this avenue. This would guarantee it a place under github.com/haskell namespace. CLC adoption does not entail any immediate changes to the project structure or existing maintainers, but gives CLC a right to install new maintainers when needed. See https://github.com/haskell/core-libraries-committee#core-libraries for more details.

**Comment by TomMD** [comment]
@Bodigrim Perfect, thanks! I'll continue the more general question in discourse and work to move entropy over.
